%% ============================================================================
%% genetic_optimizer.pl - Genetic Algorithm Optimization Module
%% ============================================================================
%% Implements a Genetic Algorithm (GA) for optimizing timetable quality.
%% The GA evolves a population of timetables over multiple generations,
%% using selection, crossover, and mutation operators to improve fitness.
%%
%% Chromosome Representation:
%%   A chromosome is a list of gene/4 terms:
%%     gene(SessionID, TeacherID, RoomID, SlotID)
%%   where SessionID = session(ClassID, SubjectID)
%%
%% Fitness Function:
%%   fitness = hard_constraint_score * 0.5
%%           + soft_constraint_score * 0.3
%%           + quality_score        * 0.2
%%   (higher is better, range 0.0 - 1.0)
%%
%% Requirements: Feature 11 (Task 28A)
%% ============================================================================

:- module(genetic_optimizer, [
    optimize_timetable_with_ga/2,
    population_initialization/2,
    fitness_function/2,
    crossover_operator/3,
    mutation_operator/2,
    selection_strategy/3,
    evolution_loop/4,
    chromosome_to_matrix/2,
    matrix_to_chromosome/2
]).

:- use_module(knowledge_base).
:- use_module(matrix_model).
:- use_module(constraints).
:- use_module(quality_scorer, [
    hard_constraint_score/2,
    workload_balance_score/2,
    room_utilization_score/2,
    schedule_compactness_score/2
]).
:- use_module(timetable_generator).
:- use_module(logging).
:- use_module(library(lists)).

:- multifile teacher/5, subject/5, room/4, timeslot/5, class/3.
:- dynamic   teacher/5, subject/5, room/4, timeslot/5, class/3.

%% ============================================================================
%% optimize_timetable_with_ga/2 - Main GA Entry Point
%% ============================================================================
%% Format: optimize_timetable_with_ga(+Options, -Result)
%%
%% Options is a dict with keys:
%%   population_size  (default 20)
%%   generations      (default 50)
%%   mutation_rate    (default 0.1)
%%   crossover_rate   (default 0.8)
%%
%% Result is a dict:
%%   timetable       - the best timetable found (matrix)
%%   fitness         - final best fitness score
%%   fitness_history - list of best fitness per generation
%%
optimize_timetable_with_ga(Options, Result) :-
    log_info('Starting Genetic Algorithm optimization'),
    % Extract options with defaults
    (get_dict(population_size, Options, PopSize) -> true ; PopSize = 20),
    (get_dict(generations,     Options, MaxGen)  -> true ; MaxGen  = 50),
    (get_dict(mutation_rate,   Options, MutRate) -> true ; MutRate = 0.1),
    (get_dict(crossover_rate,  Options, CxRate)  -> true ; CxRate  = 0.8),
    % Build initial population
    log_info('Initializing population'),
    population_initialization(PopSize, Population),
    % Run evolution loop
    log_info('Starting evolution'),
    evolution_loop(Population, MaxGen, MutRate-CxRate, EvolutionResult),
    EvolutionResult = evolution_result(BestChromosome, BestFitness, FitnessHistory),
    % Convert best chromosome back to matrix
    chromosome_to_matrix(BestChromosome, BestMatrix),
    format(atom(DoneMsg), 'GA complete. Best fitness: ~4f', [BestFitness]),
    log_info(DoneMsg),
    Result = _{
        timetable:       BestMatrix,
        fitness:         BestFitness,
        fitness_history: FitnessHistory
    }.

%% ============================================================================
%% population_initialization/2 - Create initial population
%% ============================================================================
%% Format: population_initialization(+N, -Population)
%%
%% Creates N chromosomes. The first chromosome is generated by the CSP solver
%% (if available); remaining chromosomes are random permutations.
%%
population_initialization(N, Population) :-
    N > 0,
    % Collect all sessions to schedule
    retrieve_resources(Teachers, Subjects, Rooms, Slots, Classes),
    validate_resources(Teachers, Subjects, Rooms, Slots, Classes),
    create_sessions(Classes, Subjects, Sessions),
    % Generate N chromosomes
    generate_chromosomes(Sessions, Teachers, Rooms, Slots, N, Population).

generate_chromosomes(_, _, _, _, 0, []) :- !.
generate_chromosomes(Sessions, Teachers, Rooms, Slots, N, [Chrom|Rest]) :-
    N > 0,
    random_chromosome(Sessions, Teachers, Rooms, Slots, Chrom),
    N1 is N - 1,
    generate_chromosomes(Sessions, Teachers, Rooms, Slots, N1, Rest).

%% random_chromosome/5 - Create a random chromosome
%% Assigns random (but domain-valid) teacher/room/slot to each session.
random_chromosome(Sessions, Teachers, Rooms, Slots, Chromosome) :-
    maplist(random_gene(Teachers, Rooms, Slots), Sessions, Chromosome).

random_gene(Teachers, Rooms, Slots, Session, gene(Session, TeacherID, RoomID, SlotID)) :-
    Session = session(_, SubjectID),
    % Pick a qualified teacher (or any teacher if none qualified)
    findall(T, (member(teacher(T,_,_,_,_), Teachers), qualified(T, SubjectID)), QualTeachers),
    (QualTeachers \= [] -> TeacherPool = QualTeachers ; TeacherPool = Teachers),
    random_member_from(TeacherPool, TeacherID),
    % Pick a suitable room (or any room)
    findall(R, (member(room(R,_,_,_), Rooms), check_room_suitable(R, SubjectID)), SuitRooms),
    (SuitRooms \= [] -> RoomPool = SuitRooms ; RoomPool = Rooms),
    random_member_from(RoomPool, RoomID),
    % Pick a random slot
    random_member_from(Slots, SlotTerm),
    (SlotTerm = timeslot(SlotID,_,_,_,_) -> true ; SlotID = SlotTerm).

%% random_member_from/2 - Pick a random element from a list
random_member_from([X], X) :- !.
random_member_from(List, X) :-
    length(List, Len),
    Idx is random(Len),
    nth0(Idx, List, X).

%% ============================================================================
%% fitness_function/2 - Evaluate timetable quality
%% ============================================================================
%% Format: fitness_function(+Chromosome, -Fitness)
%%
%% Fitness combines:
%%   50% hard constraint satisfaction
%%   30% soft constraint score
%%   20% quality score
%%
fitness_function(Chromosome, Fitness) :-
    chromosome_to_matrix(Chromosome, Matrix),
    % Hard constraint score
    hard_constraint_score(Matrix, HardScore),
    % Soft constraint score (simplified: use schedule compactness + workload balance)
    workload_balance_score(Matrix, WorkloadScore),
    schedule_compactness_score(Matrix, CompactnessScore),
    SoftScore is (WorkloadScore + CompactnessScore) / 2.0,
    % Room utilization score
    room_utilization_score(Matrix, RoomScore),
    % Combined fitness
    Fitness is HardScore * 0.5 + SoftScore * 0.3 + RoomScore * 0.2.

%% ============================================================================
%% chromosome_to_matrix/2 - Convert chromosome to timetable matrix
%% ============================================================================
chromosome_to_matrix(Chromosome, Matrix) :-
    get_all_rooms(Rooms),
    get_all_timeslots(Slots),
    create_empty_timetable(Rooms, Slots, EmptyMatrix),
    foldl(place_gene(Rooms, Slots), Chromosome, EmptyMatrix, Matrix).

place_gene(Rooms, Slots, gene(Session, TeacherID, RoomID, SlotID), MatIn, MatOut) :-
    Session = session(ClassID, SubjectID),
    % Find room index
    (nth0(RoomIdx, Rooms, room(RoomID,_,_,_)) -> true ; RoomIdx = 0),
    % Find slot index
    (nth0(SlotIdx, Slots, timeslot(SlotID,_,_,_,_)) -> true ; SlotIdx = 0),
    Assignment = assigned(RoomID, ClassID, SubjectID, TeacherID, SlotID),
    (catch(set_cell(MatIn, RoomIdx, SlotIdx, Assignment, MatOut), _, MatOut = MatIn) -> true ; MatOut = MatIn).

%% ============================================================================
%% matrix_to_chromosome/2 - Convert timetable matrix to chromosome
%% ============================================================================
matrix_to_chromosome(Matrix, Chromosome) :-
    get_all_assignments(Matrix, Assignments),
    maplist(assignment_to_gene, Assignments, Chromosome).

assignment_to_gene(assigned(RoomID, ClassID, SubjectID, TeacherID, SlotID),
                   gene(session(ClassID, SubjectID), TeacherID, RoomID, SlotID)).

%% ============================================================================
%% crossover_operator/3 - Combine two parent chromosomes
%% ============================================================================
%% Format: crossover_operator(+Parent1, +Parent2, -Offspring)
%%
%% Single-point crossover: split both parents at a random point and
%% combine the first half of Parent1 with the second half of Parent2.
%%
crossover_operator(Parent1, Parent2, Offspring) :-
    length(Parent1, Len),
    Len > 0,
    Point is 1 + random(Len),
    length(P1Head, Point),
    append(P1Head, _, Parent1),
    length(P2Head, Point),
    append(P2Head, P2Tail, Parent2),
    % Use head from Parent1, tail from Parent2
    % Align by session: replace genes in P1Head that match sessions in P2Tail
    append(P1Head, P2Tail, RawOffspring),
    % Deduplicate: keep only the first gene for each session
    deduplicate_chromosome(RawOffspring, Offspring).

%% deduplicate_chromosome/2 - Keep first occurrence of each session
deduplicate_chromosome([], []).
deduplicate_chromosome([Gene|Rest], [Gene|Deduped]) :-
    Gene = gene(Session, _, _, _),
    exclude(gene_session_matches(Session), Rest, Filtered),
    deduplicate_chromosome(Filtered, Deduped).

gene_session_matches(Session, gene(Session, _, _, _)).

%% ============================================================================
%% mutation_operator/2 - Randomly modify timetable assignments
%% ============================================================================
%% Format: mutation_operator(+Chromosome, -Mutated)
%%
%% For each gene, with probability proportional to mutation_rate (applied
%% externally), randomly reassign the teacher, room, or slot.
%% This predicate mutates a single randomly chosen gene.
%%
mutation_operator(Chromosome, Mutated) :-
    length(Chromosome, Len),
    Len > 0,
    MutIdx is random(Len),
    nth0(MutIdx, Chromosome, gene(Session, _, _, _)),
    Session = session(_, SubjectID),
    % Get valid resources
    get_all_teachers(Teachers),
    get_all_rooms(Rooms),
    get_all_timeslots(Slots),
    % Pick new random values
    findall(T, (member(teacher(T,_,_,_,_), Teachers), qualified(T, SubjectID)), QT),
    (QT \= [] -> TPool = QT ; TPool = Teachers),
    random_member_from(TPool, NewTeacher),
    findall(R, (member(room(R,_,_,_), Rooms), check_room_suitable(R, SubjectID)), QR),
    (QR \= [] -> RPool = QR ; RPool = Rooms),
    random_member_from(RPool, NewRoom),
    random_member_from(Slots, SlotTerm),
    (SlotTerm = timeslot(NewSlot,_,_,_,_) -> true ; NewSlot = SlotTerm),
    % Replace the gene at MutIdx
    replace_nth_gene(MutIdx, Chromosome, gene(Session, NewTeacher, NewRoom, NewSlot), Mutated).

replace_nth_gene(0, [_|T], New, [New|T]) :- !.
replace_nth_gene(N, [H|T], New, [H|R]) :-
    N > 0, N1 is N - 1,
    replace_nth_gene(N1, T, New, R).

%% ============================================================================
%% selection_strategy/3 - Tournament selection
%% ============================================================================
%% Format: selection_strategy(+Population, +FitnessMap, -Selected)
%%
%% Tournament selection: randomly pick 3 individuals and return the fittest.
%% FitnessMap is a list of Fitness-Chromosome pairs (sorted descending).
%%
selection_strategy(Population, FitnessMap, Selected) :-
    length(Population, Len),
    Len > 0,
    TournSize is min(3, Len),
    pick_tournament_candidates(FitnessMap, TournSize, Candidates),
    % Best candidate (highest fitness) wins
    sort(0, @>=, Candidates, [_-Selected|_]).

pick_tournament_candidates(_, 0, []) :- !.
pick_tournament_candidates(FitnessMap, N, [F-C|Rest]) :-
    N > 0,
    length(FitnessMap, Len),
    Idx is random(Len),
    nth0(Idx, FitnessMap, F-C),
    N1 is N - 1,
    pick_tournament_candidates(FitnessMap, N1, Rest).

%% evaluate_population/2 - Compute fitness for all chromosomes
%% Returns list of Fitness-Chromosome pairs sorted descending by fitness.
evaluate_population(Population, FitnessMap) :-
    maplist(eval_individual, Population, Pairs),
    sort(0, @>=, Pairs, FitnessMap).

eval_individual(Chromosome, Fitness-Chromosome) :-
    (catch(fitness_function(Chromosome, Fitness), _, Fitness = 0.0) -> true ; Fitness = 0.0).

%% ============================================================================
%% evolution_loop/4 - Iterate generations until convergence
%% ============================================================================
%% Format: evolution_loop(+Population, +MaxGen, +Rates, -Result)
%%
%% Rates = MutRate-CxRate
%% Result = evolution_result(BestChromosome, BestFitness, FitnessHistory)
%%
evolution_loop(Population, MaxGen, Rates, Result) :-
    evaluate_population(Population, FitnessMap),
    FitnessMap = [BestFitness0-BestChrom0|_],
    evolution_loop_(Population, FitnessMap, MaxGen, 0, Rates,
                    BestChrom0, BestFitness0, [BestFitness0], Result).

evolution_loop_(_, FitnessMap, MaxGen, Gen, _, BestChrom, BestFit, History, Result) :-
    Gen >= MaxGen,
    !,
    reverse(History, FitnessHistory),
    Result = evolution_result(BestChrom, BestFit, FitnessHistory),
    format(atom(Msg), 'Evolution complete after ~w generations', [Gen]),
    log_info(Msg).

evolution_loop_(Population, FitnessMap, MaxGen, Gen, Rates, BestChrom, BestFit, History, Result) :-
    Rates = MutRate-CxRate,
    length(Population, PopSize),
    % Generate new population via selection + crossover + mutation
    generate_new_population(Population, FitnessMap, PopSize, MutRate, CxRate, NewPopulation),
    % Evaluate new population
    evaluate_population(NewPopulation, NewFitnessMap),
    NewFitnessMap = [NewBestFit-NewBestChrom|_],
    % Elitism: keep best individual
    (NewBestFit > BestFit ->
        UpdatedBestChrom = NewBestChrom,
        UpdatedBestFit   = NewBestFit
    ;
        UpdatedBestChrom = BestChrom,
        UpdatedBestFit   = BestFit
    ),
    % Log progress every 10 generations
    Gen1 is Gen + 1,
    (0 is Gen1 mod 10 ->
        format(atom(ProgMsg), 'GA Generation ~w: best fitness = ~4f', [Gen1, UpdatedBestFit]),
        log_info(ProgMsg)
    ; true),
    evolution_loop_(NewPopulation, NewFitnessMap, MaxGen, Gen1, Rates,
                    UpdatedBestChrom, UpdatedBestFit, [UpdatedBestFit|History], Result).

%% generate_new_population/6 - Create next generation
generate_new_population(Population, FitnessMap, PopSize, MutRate, CxRate, NewPop) :-
    generate_individuals(Population, FitnessMap, PopSize, MutRate, CxRate, NewPop).

generate_individuals(_, _, 0, _, _, []) :- !.
generate_individuals(Population, FitnessMap, N, MutRate, CxRate, [Ind|Rest]) :-
    N > 0,
    % Select two parents
    selection_strategy(Population, FitnessMap, Parent1),
    selection_strategy(Population, FitnessMap, Parent2),
    % Crossover
    CxRand is random_float,
    (CxRand < CxRate ->
        crossover_operator(Parent1, Parent2, Child)
    ;
        Child = Parent1
    ),
    % Mutation
    MutRand is random_float,
    (MutRand < MutRate ->
        mutation_operator(Child, Ind)
    ;
        Ind = Child
    ),
    N1 is N - 1,
    generate_individuals(Population, FitnessMap, N1, MutRate, CxRate, Rest).

%% ============================================================================
%% End of genetic_optimizer.pl
%% ============================================================================
